import { Saint } from '../types';

const saints: Saint[] = [
  {
    nombre: "Mu",
    signo: "Aries",
    cloth: "Oro",
    constelacion: "Aries",
    fechaNacimiento: "27 de marzo",
    origen: "Tíbet (entrenamiento en Jamir)",
    alturaCm: 182,
    pesoKg: 75,
    tipoSangre: "A",
    tecnicas: ["telequinesis", "teletransportación"],
    datoRelevante:
      "Repara las armaduras y posee el poder psíquico más fuerte entre los Santos Dorados.",
  },
  {
    nombre: "Aldebarán",
    signo: "Tauro",
    cloth: "Oro",
    constelacion: "Tauro",
    fechaNacimiento: "8 de mayo",
    origen: "Brasil",
    alturaCm: 210,
    pesoKg: 130,
    tipoSangre: "B",
    tecnicas: ["Great Horn"],
    datoRelevante: "Es el más fuerte físicamente entre los Santos Dorados.",
  },
  {
    nombre: "Saga",
    signo: "Géminis",
    cloth: "Oro",
    constelacion: "Géminis",
    fechaNacimiento: "30 de mayo",
    origen: "Grecia",
    datoRelevante:
      "Posee doble personalidad y llegó a usurpar el Patriarcado.",
  },
  {
    nombre: "Deathmask",
    signo: "Cáncer",
    cloth: "Oro",
    constelacion: "Cáncer",
    fechaNacimiento: "24 de junio",
    origen: "Italia",
    datoRelevante: "Conocido por su extrema crueldad y sadismo.",
  },
  {
    nombre: "Aiolia",
    signo: "Leo",
    cloth: "Oro",
    constelacion: "Leo",
    fechaNacimiento: "16 de agosto",
    origen: "Grecia",
    alturaCm: 185,
    pesoKg: 85,
    tipoSangre: "O",
    tecnicas: ["Lightning Bolt", "Lightning Plasma", "Photon Burst"],
    datoRelevante:
      "Hermano de Aiolos; se convirtió en Santo Dorado muy joven y lucha con orgullo.",
  },
  {
    nombre: "Shaka",
    signo: "Virgo",
    cloth: "Oro",
    constelacion: "Virgo",
    fechaNacimiento: "19 de septiembre",
    origen: "India",
    datoRelevante:
      "Conocido como 'el hombre más cercano a Dios', experto en técnicas espirituales.",
  },
  {
    nombre: "Dohko",
    signo: "Libra",
    cloth: "Oro",
    constelacion: "Libra",
    fechaNacimiento: "20 de octubre (siglo XVIII)",
    origen: "China",
    datoRelevante:
      "Maestro de Shiryu y uno de los Santos Dorados más longevos.",
  },
  {
    nombre: "Milo",
    signo: "Escorpio",
    cloth: "Oro",
    constelacion: "Escorpio",
    fechaNacimiento: "8 de noviembre",
    origen: "Grecia (isla de Milo)",
    tecnicas: ["Scarlet Needle", "Restriction"],
    datoRelevante:
      "Su técnica causa dolor extremo y es considerado uno de los más poderosos.",
  },
  {
    nombre: "Aiolos",
    signo: "Sagitario",
    cloth: "Oro",
    constelacion: "Sagitario",
    fechaNacimiento: "30 de noviembre",
    origen: "Grecia",
    datoRelevante:
      "Protegió a Atenea cuando era bebé, sacrificándose por ella.",
  },
  {
    nombre: "Shura",
    signo: "Capricornio",
    cloth: "Oro",
    constelacion: "Capricornio",
    fechaNacimiento: "12 de enero",
    origen: "España",
    tecnicas: ["Excalibur", "Double Excalibur"],
    datoRelevante:
      "Se sacrificó para salvar a Shiryu usando técnicas basadas en Excalibur.",
  },
  {
    nombre: "Camus",
    signo: "Acuario",
    cloth: "Oro",
    constelacion: "Acuario",
    fechaNacimiento: "7 de febrero",
    origen: "Francia",
    tecnicas: ["Diamond Dust", "Freezing Coffin", "Aurora Execution"],
    datoRelevante:
      "Fue nombrado Santo Dorado con solo 7 años; es maestro de Hyōga.",
  },
  {
    nombre: "Aphrodite",
    signo: "Piscis",
    cloth: "Oro",
    constelacion: "Piscis",
    fechaNacimiento: "10 de marzo",
    origen: "Suecia",
    datoRelevante: "Conocido por su belleza y sus rosas letales.",
  },
  {
    nombre: "Seiya",
    signo: "Sagitario",
    cloth: "Bronce",
    constelacion: "Pegaso",
    fechaNacimiento: "1 de diciembre",
    origen: "Japón",
    alturaCm: 165,
    pesoKg: 53,
    tipoSangre: "B",
    tecnicas: [
      "Pegasus Ryūsei Ken",
      "Pegasus Rolling Crash",
      "Pegasus Suisei Ken",
    ],
    datoRelevante:
      "Es el protagonista principal y se caracteriza por su valentía y determinación.",
  },
  {
    nombre: "Shiryu",
    signo: "Libra",
    cloth: "Bronce",
    constelacion: "Dragón",
    fechaNacimiento: "4 de octubre",
    origen: "Japón",
    alturaCm: 174,
    pesoKg: 53,
    tipoSangre: "A",
    tecnicas: [
      "Rozan Shōryūha",
      "Rozan Ryūhishō",
      "Rozan Hyakuryūha",
      "Rozan Kōryūha",
      "Excalibur",
    ],
    datoRelevante:
      "Su maestro fue Dohko de Libra, y se entrenó en las Cascadas de Rozan en China.",
  },
  {
    nombre: "Hyōga",
    signo: "Acuario",
    cloth: "Bronce",
    constelacion: "Cisne",
    fechaNacimiento: "21 de enero",
    origen: "Rusia",
    alturaCm: 173,
    pesoKg: 60,
    tipoSangre: "O",
    tecnicas: ["Diamond Dust", "Aurora Thunder Attack", "Aurora Execution"],
    datoRelevante:
      "Fue discípulo de Camus de Acuario y se entrenó en Siberia Oriental.",
  },
  {
    nombre: "Shun",
    signo: "Virgo",
    cloth: "Bronce",
    constelacion: "Andrómeda",
    fechaNacimiento: "9 de septiembre",
    origen: "Japón",
    alturaCm: 165,
    pesoKg: 51,
    tipoSangre: "A",
    tecnicas: [
      "Cadena Nebular",
      "Nebulosa de Andrómeda",
      "Defensa Giratoria",
      "Onda del Trueno",
    ],
    datoRelevante:
      "Es el hermano menor de Ikki y se caracteriza por su personalidad pacifista.",
  },
  {
    nombre: "Ikki",
    signo: "Leo",
    cloth: "Bronce",
    constelacion: "Fénix",
    fechaNacimiento: "15 de agosto",
    origen: "Japón",
    alturaCm: 175,
    pesoKg: 62,
    tipoSangre: "AB",
    tecnicas: [
      "Phoenix Fire",
      "Phoenix Illusion",
      "Phoenix Genma Ken",
      "Phoenix Wing",
    ],
    datoRelevante:
      "Fue entrenado en la Isla de la Reina Muerte por su maestro Guilty.",
  },
  {
    nombre: "Marin",
    signo: "Águila",
    cloth: "Plata",
    constelacion: "Águila",
    fechaNacimiento: "16 de octubre",
    origen: "Japón",
    tecnicas: ["Meteoro", "Destello del Águila", "Golpe Vacío"],
    datoRelevante: "Es la maestra de Seiya y hermana de Seika.",
  },
  {
    nombre: "Shaina",
    signo: "Ofiuco",
    cloth: "Plata",
    constelacion: "Ofiuco",
    fechaNacimiento: "27 de marzo",
    origen: "Italia",
    tecnicas: ["Garra de Trueno"],
    datoRelevante: "Fue la maestra de Cassios y rival de Seiya.",
  },
  {
    nombre: "Algol",
    signo: "Perseo",
    cloth: "Plata",
    constelacion: "Perseo",
    fechaNacimiento: "25 de enero",
    origen: "Grecia",
    tecnicas: ["Perseo Gorgon", "Perseo Gorgon II"],
    datoRelevante:
      "Es uno de los Santos de Plata enviados para detener a los Caballeros de Bronce.",
  },
  {
    nombre: "Misty",
    signo: "Lagarto",
    cloth: "Plata",
    constelacion: "Lagarto",
    fechaNacimiento: "5 de junio",
    origen: "Francia",
    tecnicas: ["Lagarto Giga", "Lagarto Giga II"],
    datoRelevante: "Es derrotado por Seiya en la Casa de Aries.",
  },
  {
    nombre: "Moses",
    signo: "Ballena",
    cloth: "Plata",
    constelacion: "Ballena",
    fechaNacimiento: "12 de febrero",
    origen: "Grecia",
    tecnicas: ["Ballena Giga", "Ballena Giga II"],
    datoRelevante: "Es derrotado por Seiya en la Casa de Tauro.",
  },
  {
    nombre: "Asterion",
    signo: "Perros de Caza",
    cloth: "Plata",
    constelacion: "Perros de Caza",
    fechaNacimiento: "3 de septiembre",
    origen: "Grecia",
    tecnicas: ["Perros de Caza Giga", "Perros de Caza Giga II"],
    datoRelevante: "Es derrotado por Seiya en la Casa de Géminis.",
  },
  {
    nombre: "Jamian",
    signo: "Cuervo",
    cloth: "Plata",
    constelacion: "Cuervo",
    fechaNacimiento: "18 de noviembre",
    origen: "Grecia",
    tecnicas: ["Cuervo Giga", "Cuervo Giga II"],
    datoRelevante: "Es derrotado por Seiya en la Casa de Cáncer.",
  },
  {
    nombre: "Dio",
    signo: "Mosca",
    cloth: "Plata",
    constelacion: "Mosca",
    fechaNacimiento: "22 de abril",
    origen: "Grecia",
    tecnicas: ["Mosca Giga", "Mosca Giga II"],
    datoRelevante: "Es derrotado por Seiya en la Casa de Leo.",
  },
  {
    nombre: "Sirius",
    signo: "Can Mayor",
    cloth: "Plata",
    constelacion: "Can Mayor",
    fechaNacimiento: "8 de diciembre",
    origen: "Grecia",
    tecnicas: ["Can Mayor Giga", "Can Mayor Giga II"],
    datoRelevante: "Es derrotado por Seiya en la Casa de Virgo.",
  },
  {
    nombre: "Algethi",
    signo: "Hércules",
    cloth: "Plata",
    constelacion: "Hércules",
    fechaNacimiento: "30 de julio",
    origen: "Grecia",
    tecnicas: ["Hércules Giga", "Hércules Giga II"],
    datoRelevante: "Es derrotado por Seiya en la Casa de Libra.",
  },
  {
    nombre: "Ptolemy",
    signo: "Flecha",
    cloth: "Plata",
    constelacion: "Flecha",
    fechaNacimiento: "14 de marzo",
    origen: "Grecia",
    tecnicas: ["Flecha Giga", "Flecha Giga II"],
    datoRelevante: "Es derrotado por Seiya en la Casa de Escorpio.",
  },
  {
    nombre: "Rigel",
    signo: "Orión",
    cloth: "Plata",
    constelacion: "Orión",
    fechaNacimiento: "2 de mayo",
    origen: "Grecia",
    tecnicas: ["Orión Giga", "Orión Giga II"],
    datoRelevante: "Es derrotado por Seiya en la Casa de Sagitario.",
  },
  {
    nombre: "Geist",
    signo: "Lira",
    cloth: "Plata",
    constelacion: "Lira",
    fechaNacimiento: "17 de septiembre",
    origen: "Grecia",
    tecnicas: ["Lira Giga", "Lira Giga II"],
    datoRelevante: "Es derrotado por Seiya en la Casa de Capricornio.",
  },
  {
    nombre: "Spartan",
    signo: "Escorpión",
    cloth: "Plata",
    constelacion: "Escorpión",
    fechaNacimiento: "9 de octubre",
    origen: "Grecia",
    tecnicas: ["Escorpión Giga", "Escorpión Giga II"],
    datoRelevante: "Es derrotado por Seiya en la Casa de Acuario.",
  },
  {
    nombre: "Agora",
    signo: "Loto",
    cloth: "Plata",
    constelacion: "Loto",
    fechaNacimiento: "27 de agosto",
    origen: "Grecia",
    tecnicas: ["Loto Giga", "Loto Giga II"],
    datoRelevante: "Es derrotado por Seiya en la Casa de Piscis.",
  },
];

export default saints;